# Generated by Django 4.2.7 on 2025-09-12 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Удобство',
                'verbose_name_plural': 'Удобства',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cottage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ночь')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Коттедж',
                'verbose_name_plural': 'Коттеджи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CottageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cottages/', verbose_name='Изображение')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основное')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('cottage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cottages.cottage', verbose_name='Коттедж')),
            ],
            options={
                'verbose_name': 'Изображение коттеджа',
                'verbose_name_plural': 'Изображения коттеджей',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CottageAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cottages.amenity', verbose_name='Удобство')),
                ('cottage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='cottages.cottage', verbose_name='Коттедж')),
            ],
            options={
                'verbose_name': 'Удобство коттеджа',
                'verbose_name_plural': 'Удобства коттеджей',
                'unique_together': {('cottage', 'amenity')},
            },
        ),
    ]
