# Generated by Django 4.2.7 on 2025-09-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callbackrequest',
            name='name',
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='first_name',
            field=models.CharField(default='Не указано', max_length=50, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='last_name',
            field=models.CharField(default='Не указано', max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Отчество'),
        ),
    ]
