global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@cottage-booking.com'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'telegram-alerts'

receivers:
  - name: 'telegram-alerts'
    webhook_configs:
      - url: 'https://api.telegram.org/bot{{ .TELEGRAM_BOT_TOKEN }}/sendMessage'
        send_resolved: true
        title: '🚨 Cottage Booking Alert'
        text: |
          {{ range .Alerts }}
          🔥 **{{ .Annotations.summary }}**
          
          📊 **Описание:** {{ .Annotations.description }}
          🏷️ **Серьезность:** {{ .Labels.severity }}
          ⏰ **Время:** {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          
          {{ if .Labels.instance }}
          🖥️ **Сервер:** {{ .Labels.instance }}
          {{ end }}
          
          {{ if eq .Status "firing" }}
          🔴 **Статус:** Активен
          {{ else }}
          🟢 **Статус:** Решен
          {{ end }}
          
          ---
          {{ end }}

  - name: 'email-alerts'
    email_configs:
      - to: 'admin@cottage-booking.com'
        subject: '🚨 Cottage Booking Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Time: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
